### ISSUE TITLE
Any way to use next/prev-line with evil-leader?

### ISSUE THREAD

**Issue by NicholasTD07** [PythonNut/evil-easymotion#10]
I enjoys being able to jump to specific lines above/below current line. I use evil-leader to define my own leader key based key mappings. And I would like to add next/prev-line into my leader key mappings. However, I couldn't get it to work. Could you give me a hand on this? I am pretty new to Emacs and Elisp.

Following is my config:

```elisp
(evil-leader/set-leader "<SPC>")
(evil-leader/set-key
  "j" '(evilem-create 'next-line
         nil nil ((temporary-goal-column (current-column))
         (line-move-visual nil)))
))
```

Thank you for this awesome port!

PS.
If you haven't seen it yet, EasyMotion has some very cool new features in version 2.0. https://github.com/Lokaltog/vim-easymotion#new-features-in-version-20

**Comment by PythonNut** [comment]
Does the following work?
```emacs
(evil-leader/set-key
  "j" '(evilem-create 'next-line
         nil nil ((temporary-goal-column (current-column))
         (line-move-visual nil)))))
```

**Comment by PythonNut** [comment]
I have seen EM2. Let me enumerate it's features.

* **Two key highlighting**

This is a limitation of [`ace-jump-mode`](https://github.com/winterTTr/ace-jump-mode), and needs to be fixed there. When fixed, the changes will percolate up without my intervention (hopefully). You can track the progress of that feature at [winterTTr/**ace-jump-mode** #32](https://github.com/winterTTr/ace-jump-mode/issues/32).

* **Bidirectional motions**

Currently unsupported. Truth be told, they would not be terribly difficult to add, I think, but they sort of strike me as being gimmicky. (Correct me if I'm wrong!) The mental load of choosing the direction to travel in was never more than the load of choosing from more options.

I could add this, and indeed I might.

* **2-character search motion**

See [hlissner/**evil-snipe**](https://github.com/hlissner/evil-snipe).

> Evil-snipe marries vim-sneak and vim-seek with Emacs, for evil. How evil.

* **N-character search motion**

This is harder. I've actually worked a bit with the Emacs `isearch` system, but looking this head-on, it seems like a lot of work. But all is not lost. You can:
```emacs
(evilem-define (kbd-pfx "n") #'evil-search-next)
(evilem-define (kbd-pfx "N") #'evil-search-previous)
```

Then, you can search and select from the matches onscreen. I know it's not exactly the same, but maybe it will do?

* **Within line motion**

You can do this now by defining the functions with care.

```emacs
(defun forward-word-in-line ()
  (interactive)
  (let* ((pt (point)) (line (line-number-at-pos)))
    (goto-char
      (save-excursion (forward-word)
        (if (eq line (line-number-at-pos))
          (point)
          pt)))))

(evilem-define (kbd "SPC q") 'forward-word-in-line)
```

This was coded hastily, but you get the idea. Here, the extensibility of EE is a good thing.

* **hjkl motions**

It _looks_ like you can do something like what you're trying to do to achieve this.

* **Smartcase & Smartsign**

> `ace-jump-mode-case-fold` is a variable defined in `ace-jump-mode.el.

> Documentation:
> If non-nil, the ace-jump mode will ignore case.

> The default value is set to the same as `case-fold-search`.

* **Migemo feature (for Japanese user)**

I am Japanese, actually, but I've not used that. Emacs is good at IMEs so I suppose most users will <kbd>C-\\</kbd> <kbd>japanese</kbd> and just type out Japanese for real.

* **Repeat motions**

These are hard. I'm not sure how I'm going to support these, but I would like to. This will require a good look at `evil-repeat` and company.


--------------------------------------

It seems to me that EasyMotion 2.0 has many nice things, but ultimately the majority of them are rather minor in the real world (with the exception of multidepth hinting, which is huge). This all comes, I suspect, at the expense of many lines of code.

Oddly, EasyMotion seems to have adopted the Emacs philosophy of doing absolutely everything, which is cool. It's hard, though to quadruple the size of my codebase if the benefits are so minor. For some of these features, I'm tentatively okay with letting them be.

I know this isn't what you want to hear, but I'm spread desperately thin. College apps inexorably approach.

**Comment by NicholasTD07** [comment]
Thanks for such a fast and through reply.

I actually only use a few of the new features in EM2. I use within-line motion for `t` and `f` in operator mode(e.g. after pressing `d`/`c` in normal mode), bidirectional `t` and `f` in normal mode and line motions(easy-motion-j/k).

I tried the snippet you gave me. Emacs gives me this error when I try it by hitting `SPC j`.

```
command-execute: Wrong type argument: commandp,
(evilem-create (quote next-line) nil nil
  ((temporary-goal-column (current-column)) (line-move-visual nil)))
```

**Comment by PythonNut** [comment]
I actually forgot to change your code before I posted it. Try this:

```emacs
(evil-leader/set-key
  "j" (evilem-create 'next-line
         nil nil ((temporary-goal-column (current-column))
         (line-move-visual nil)))))
```

**Comment by NicholasTD07** [comment]
Sorry for getting back so late.

I tried this snippet. It works! However, when `SPC j` is hit, it first goes down half a page or so like there's a call for `emacs/go-down-half-page!` before the actual code is run.

Hope you have a good day.

**Comment by PythonNut** [comment]
Strange. I don't see that here. Can you reproduce it in `emacs -Q`? If you can't, then please send me your config, so I can devise a workaround.

**Comment by NicholasTD07** [comment]
I tried `emacs -Q -l myconfig.el, still having this problem. 

This is my current config.
https://github.com/NicholasTD07/dotfiles/blob/master/.emacs.d.nickTD/init.el#L164

PS.
Another thing, well, actually two, about evil and ace-jump:
When I try to use ace-jump-char-mode in operator mode, it takes a much longer time to render the query results than normal and visual modes. For example, `df<char>` vs `vf<char>`. And when I cancel the `df` motion with `C-g`, it deletes the character where my cursor was before `df<char>`.
Are you having these two problems? Or can you reproduce them?

**Comment by PythonNut** [comment]
> When I try to use ace-jump-char-mode in operator mode, it takes a much longer time to render the query results than normal and visual modes. 

Yes, I do see this. On my fast laptop, the delay for operators isn't so bad (~1s) so I live with it. But, say, on my raspberry pi the difference is staggeringly large (~10s).

 > And when I cancel the df motion with C-g, it deletes the character where my cursor was before df<char>.

I have not seen this, actually.

Give me a day or two to bisect your config and reproduce the issues. Would you mind opening a new issue for each?

**Comment by NicholasTD07** [comment]
Sorry to get back really long.

I don't think these two are problems caused by evil-easymotion. Because when I use evil with ace-jump-char-mode alone, I have these problem too.

**Comment by PythonNut** [comment]
@NicholasTD07 ah, then you might want to pay the [`evil-mode`](https://bitbucket.org/lyro/evil/wiki/Home) devs a visit. Unfortunately, they're not on GH, so they're a bit harder to contact, I'm afraid.

**Comment by PythonNut** [comment]
@NicholasTD07 

> I tried this snippet. It works! However, when SPC j is hit, it first goes down half a page or so like there's a call for emacs/go-down-half-page! before the actual code is run.

Try the most recent version, I think it might contain a fix.
