### ISSUE TITLE
leader j moves down screen

### ISSUE THREAD

**Issue by huaoguo** [PythonNut/evil-easymotion#11]
Leader k is OK.
But leader j will cause the cursor move down a screen, like ctrl - f.
Only I has this bug?

**Comment by huaoguo** [comment]
In ruby and scss mode is ok, only coffeescript and javascript has this problem.

**Comment by PythonNut** [comment]
Motions in `evil-easymotion` can move the window, but I take care to save the window state and reset it, much like `save-excursion`.

Give me some time to reproduce. This week is very crazy for me, and I don't think I'll have the time.

**Comment by huaoguo** [comment]
OK

**Comment by huaoguo** [comment]
I find the problem, when the point moves to the end of the buffer, the screen auto moves down.
But I dont know why previous-line works well.

**Comment by huaoguo** [comment]
I konw, when point reach begin of buffer, it doesn't automaticly move up screen, but when reach end of buffer, it does. So cause this bug.

**Comment by huaoguo** [comment]
I solve this bug, I will push a pull request later.

**Comment by huaoguo** [comment]
https://github.com/PythonNut/evil-easymotion/pull/12
Take a look!
