### ISSUE TITLE
Docrequest: what makes `evil-easymotion` different from avy/snipe etc?

### ISSUE THREAD

**Issue by endrebak** [PythonNut/evil-easymotion#17]
And could you please post a guide on how to use it? Does it work with `d`/`t` etc? How do I install it?

**Comment by PythonNut** [comment]
Hm... I'll work on a short guide.

>  Does it work with d/t etc?

Yes, it works with all operators and motions.

> How do I install it?
<kbd>M-x</kbd> `package-install` <kbd>RET</kbd> `evil-easymotion` <kbd>RET</kbd>

**Comment by endrebak** [comment]
Sorry, I just really think it hampers adoption that you can't really tell what it does exactly. I even tried looking at the vim-easymotion page, but I wasn't sure what it does that isn't covered by other packages.

You do not need to write much; just 1) this is how you install it and then 2) try out these awesome commands.

**Comment by PythonNut** [comment]
@endrebak 

Sorry if I was unclear, I _will_ write a guide, but I'm going to be traveling, and I can't do it right now.

**Comment by PythonNut** [comment]
@endrebak is the new README any better?

**Comment by endrebak** [comment]
Very neat, so `SPC e` etc would list all end of words and so on. Will try out soon.
