### ISSUE TITLE
Compile error from paradox, 24.5 os x

### ISSUE THREAD

**Issue by endrebak** [PythonNut/evil-easymotion#18]
```
Compiling file /Users/endrebakkenstovner/.emacs.d/elpa/evil-easymotion-20150624.1526/evil-easymotion-autoloads.el at Wed Jul 15 01:08:18 2015
Entering directory `/Users/endrebakkenstovner/.emacs.d/elpa/evil-easymotion-20150624.1526/'

Compiling file /Users/endrebakkenstovner/.emacs.d/elpa/evil-easymotion-20150624.1526/evil-easymotion-pkg.el at Wed Jul 15 01:08:18 2015

Compiling file /Users/endrebakkenstovner/.emacs.d/elpa/evil-easymotion-20150624.1526/evil-easymotion.el at Wed Jul 15 01:08:18 2015
evil-easymotion.el:165:1:Error: Symbol's function definition is void: evilem-unquote

Compiling no file at Wed Jul 15 01:08:19 2015
```

**Comment by PythonNut** [comment]
Interesting. I'll take a look.

**Comment by PythonNut** [comment]
@endrebak that function is defined [here](https://github.com/PythonNut/evil-easymotion/blob/master/evil-easymotion.el#L81). Can you try installing without paradox?

**Comment by endrebak** [comment]
Will do in two weeks, promised my gf not to use the computer during my vacation (using phone :) )

**Comment by PythonNut** [comment]
Sure thing.

**Comment by PythonNut** [comment]
@endrebak bump. :)

**Comment by endrebak** [comment]
Tried with `package-install-packages` instead and it still did not work.

**Comment by PythonNut** [comment]
Hm... I suppose the next step is to try in `emacs -Q`.

**Comment by endrebak** [comment]
My keyboard is completely remapped and does not work well with term emacs; otherwise I would have reported how it went (could not get it to work.)

**Comment by PythonNut** [comment]
`emacs -Q` runs in GUI, no?

**Comment by endrebak** [comment]
No, but I can turn of my remapping (doh - its getting late here). Will try.

**Comment by endrebak** [comment]
Actually, M-x did not work in -q mode since then meta can't be invoked on OS X afaics.

**Comment by PythonNut** [comment]
Hm... If you want I can cook up something that won't require Meta, but you should probably get some sleep. :)

**Comment by endrebak** [comment]
No need, but thanks for the offer :)

**Comment by pengux** [comment]
I have the same problem, has tried both in terminal and Cocoa Emacs

**Comment by PythonNut** [comment]
@pengux @endrebak ah, now I see what's going on. This should be fixed.
