### ISSUE TITLE
Symbol's value as variable is void: evilem-motion-evil-forward-word-begin

### ISSUE THREAD

**Issue by edvail** [PythonNut/evil-easymotion#19]
Hi,

When I put ```(evilem-default-keybindings "SPC")``` in the init.el i'm getting following error on startup:
```
Symbol's value as variable is void: evilem-motion-evil-forward-word-begin
```

**Comment by PythonNut** [comment]
Hey, just curious, but does byte-compiling `init.el` fix the problem? (I understand that's not a solution, but it will help me understand what's going on.)

**Comment by edvail** [comment]
shame on me, but I don't know how to do that. Will try to google.

**Comment by edvail** [comment]
same thing:
```
Warning (initialization): An error occurred while loading `c:/cygwin64/home/edil/.emacs.d/init.elc':

Symbol's value as variable is void: evilem-motion-evil-forward-word-begin
```

**Comment by PythonNut** [comment]
Thanks. I'll get to this as soon as I can, but my next few days are looking pretty swamped, so I can't say on the timeframe.

**Comment by PythonNut** [comment]
Thanks. I'll get to this as soon as I can, but my next few days are looking pretty swamped, so I can't say on the timeframe.

**Comment by PythonNut** [comment]
So this doesn't reproduce on my development Emacs, but it does on my regular Emacs, which makes it one of the strangest Emacs bugs I've every seen.

**Comment by PythonNut** [comment]
Okay, so strangely I can't reproduce it now. Adding the repo, manually installing the package and running `(evilem-default-keybindings "SPC")` works fine on my Emacs 24.5.

**Comment by PythonNut** [comment]
You might have some luck just deleting the package and starting from scratch.

**Comment by edvail** [comment]
I have deleted my .emacs.d folder, except init.el and custom.el.
init.el reinstalled all my packages.
Now seems evil-easymotion works as expected.
Thank you.

**Comment by PythonNut** [comment]
I admit, very strange...

Thanks for the report! I've been chasing various errors for a while.

**Comment by edvail** [comment]
maybe somehow relatied to the session.el

**Comment by PythonNut** [comment]
Maybe... but I never deleted my session.

**Comment by PythonNut** [comment]
Hm... I just saw this pop up again.

**Comment by hlissner** [comment]
Happens to me when I install evil-easymotion through Cask. Works fine when cloned directly though.

**Comment by PythonNut** [comment]
I honestly don't know why this happens. It comes and goes. I think it has something to do with byte-compilation.

**Comment by PythonNut** [comment]
Finally tracked this down.

**Comment by hlissner** [comment]
Nice! Works like a charm!
