### ISSUE TITLE
Error: (end-of-buffer) [15459 times] — motions not working when bob or eob is visible

### ISSUE THREAD

**Issue by hlissner** [PythonNut/evil-easymotion#20]
1. Scroll to end (or beginning) of a non-empty buffer.
2. Invoke any of evil-easymotion's forward motions (or backward if at beginning)
3. The motion fails, and Emacs hangs and must be <kbd>C-g</kbd>'d out of its stupor, revealing an error message.

Here are some examples of the error messages I get when invoked from anywhere in a 2 line document.

* <kbd>SPC k</kbd> `Error: (beginning-of-buffer) [24811 times]`
* <kbd>SPC j</kbd> `Error: (end-of-buffer) [16032 times]`
* <kbd>SPC w</kbd> `Error: (end-of-buffer) [18530 times]`
* <kbd>SPC f -</kbd> `Error: (user-error "Cant'd find -") [42982 times]` (even when the character exists and should be found)

Perhaps `evilem-collect`'s loop isn't terminating properly (i.e. not handling the demoted error correctly) or a recent avy update caused a regression?

---

I've tested this only evil + evil-easymotion, so it's not a plugin conflict. And on Emacs 24.5 and 25.0, using evil-mode v1.2.2 (20150818.1313) and avy v0.3 (20150824.211).

My evil-easymotion config is simply:

```
(require 'evil-easymotion)
(evilem-default-keybindings "SPC")
```

**Comment by PythonNut** [comment]
@hlissner sorry, that would be me being stupid in ddbe67. Things should work now.

**Comment by hlissner** [comment]
Works fine now, thanks!
