### ISSUE TITLE
Evil-Snipe Integration Slow When Used With Operators

### ISSUE THREAD

**Issue by noctuid** [PythonNut/evil-easymotion#21]
The highlights take about half a second to appear at the top, whereas they appear pretty much instantly when the evil snipe motion is used by itself.

**Comment by PythonNut** [comment]
I admit, I don't know why this is.

**Comment by PythonNut** [comment]
@noctuid it seems to have improved. Do you still experience this problem?

**Comment by noctuid** [comment]
No, it's fast now. Thanks.
