### ISSUE TITLE
Option to Have All Letters Necessary for Jump Appear Initially

### ISSUE THREAD

**Issue by noctuid** [PythonNut/evil-easymotion#22]
For example, with `avy-goto-char`, when there are not enough letters in `avy-keys` to cover all the matches on screen, the first key that the user needs to press will be highlighted in one colour and the next key the user needs to press will be highlighted in a different colour. With evil-easymotion, if there aren't enough keys to cover all the matches, only the first key the user needs to press will be shown initially. Only after they press the first key will they see the highlighted letter corresponding to the next key they need to press to jump to a match. It would be nice if evil-easymotion acted like avy and only did this in the case where there is overlap between matches, and there isn't enough space to show multiple characters.

**Comment by PythonNut** [comment]
@noctuid see the variable `evilem-style`. I've set it to default to the same value as the normal `avy-style` in 115d6741f6f2eb7f1725a563a7976d0d3d6d05fd, which should make for a better user experience.

**Comment by noctuid** [comment]
Ah thank you. I think it makes a better default.
