### ISSUE TITLE
Option to call motion from window start instead of the point

### ISSUE THREAD

**Issue by noctuid** [PythonNut/evil-easymotion#27]
In some cases I think I'd like to just use a single key for upward and downward movement. This would be especially useful for motions that jump over large areas (resulting in few overlays). This can basically be achieved already with something like this:
```
(evilem-create #'next-line
               :pre-hook (goto-char (window-start))
               :bind ((scroll-margin 0)
                      ...))
```

The point also needs to be saved to some variable in the `pre-hook` and restored in the `post-hook` if the user didn't jump anywhere (which is a bit messy). It would be nice if there was a keyword argument to start collection from `(window-start)`.

**Comment by PythonNut** [comment]
Why not add (point (window-start)) to `:bind`?

**Comment by noctuid** [comment]
Do you check to see if `point` is bound and use that to move the point? That doesn't work for me. Or are you suggesting doing this instead of adding a keyword argument? I could override `(point)`, but that would break collection.

**Comment by PythonNut** [comment]
Wait, sorry. This will require a bit more thinking out.

**Comment by PythonNut** [comment]
@noctuid I've added the ability to pass a list of motions to `evilem-define` and company in https://github.com/PythonNut/evil-easymotion/commit/42bd507a417acafb149f6f5490470134dcbd7223

```emacs
(evilem-define (kbd "SPC j") (list #'next-line
                                   #'previous-line)
               :pre-hook (setq evil-this-type 'line)
               :bind ((temporary-goal-column (current-column))
                      (line-move-visual nil)))
```

Do you still want to have an option to set the starting point?

**Comment by noctuid** [comment]
I think that's just as good of a solution. I can't think of any motions I'd want to use that don't have a backward and forward  version. Thanks!
