### ISSUE TITLE
Allow all evilem motions push position onto the jump list

### ISSUE THREAD

**Issue by sooheon** [PythonNut/evil-easymotion#29]
Currently, issuing an evil-em movement does not work seamlessly with the jump list. If I have points A B and C in the buffer, and I moved from A to B with a regular evil motion, then jump from B to C with evil-em, `C-o` will take me to A, not B. Neither can I jump back to C with `C-i`. 

Adding `(evil--jumps-push)` to both :pre-hook and :post-hook solves the issue. Do you think it's worth making this a default?

**Comment by PythonNut** [comment]
> Adding `(evil--jumps-push)` to both `:pre-hook` and `:post-hook` solves the issue. Do you think it's worth making this a default?

I'm not sure. I generally use <kbd>C-i</kbd> and <kbd>C-o</kbd> for jumps beyond the visible portion of the buffer. Do you think this would be a good default? I tend to think that most motions do not move far enough to warrant an item in the jump list.

**Comment by sooheon** [comment]
Hm, I was under the impression that in vim, search motions like f/t were added to the jumplist. I was wrong, so I agree it makes sense not to have this behaviour default. It's strange that every snipe motion pushes to jumplist then--I'll raise the issue over there.

**Comment by braham-snyder** [comment]
obviously understandable if you don't want to make it a default, but if you're interested in defaulting to what the original does, it adds to the jumplist: https://github.com/easymotion/vim-easymotion/pull/36

**Comment by PythonNut** [comment]
@braham-snyder oh sorry, I must have missed this. Having had more time with `evil-easymotion`, I think this would be a good default behavior.
