### ISSUE TITLE
Symbol's function definition is void: avy-window-list

### ISSUE THREAD

**Issue by PythonNut** [PythonNut/evil-easymotion#31]

**Comment by xueeinstein** [comment]
I met the same issue, any fix?

**Comment by PythonNut** [comment]
I haven't managed to reproduce it again, so I'm not really sure what's going on. Please keep me posted if you figure it out.

**Comment by PythonNut** [comment]
Ah. I see what's the problem now.

**Comment by PythonNut** [comment]
Ah. I think I know what the problem is. @xueeinstein can you confirm the fix?

**Comment by xueeinstein** [comment]
It works. Thanks for your fix!
