### ISSUE TITLE
optionally sort jump points

### ISSUE THREAD

**Issue by wbolster** [PythonNut/evil-easymotion#34]
when building custom motions by combining multiple jump functions, the resulting jump points will be in the order returned by those jump functions. it would be great to have those sorted. possibilities:

* no sorting (current behaviour)
* sort from top of visible window to bottom of visible window
* sort starting from point (cursor position) downwards, with a wrap-around at the bottom to the top
* the inverse of the previous one: from point upwards, with wrap-around at the top to the bottom

background info: i use this custom motion for jumping around in python code, but the ordering feels a bit random (though i ordered the functions in such a way that it is quite okay):

```elisp
(evilem-make-motion
 my-easymotion-python
 (list
  ;; Collect interesting positions around point, and all visible
  ;; blocks in the window. Results are ordered: forward after point,
  ;; then backward from point.
  'python-nav-end-of-statement 'python-nav-end-of-block 'python-nav-forward-block
  'python-nav-beginning-of-statement 'python-nav-beginning-of-block 'python-nav-backward-block)
 :pre-hook (setq evil-this-type 'line))
```

**Comment by PythonNut** [comment]
Hey! Sorry it took me so long to fix this. Ever since my job got crazy, it's been hard to find the time. 

I've added a new parameter `:collect-postprocess`, which is documented in the [`README`](https://github.com/PythonNut/evil-easymotion/blob/master/README.md). In addition, the new default behavior should be quite reasonable even for multiple motions.

**Comment by wbolster** [comment]
awesome, thanks a lot. i'll try it out soon.

oh, and no need to apologise for late responses. especially not if you actually implemented something to address an issue! as a sometimes burnt out oss maintainer i know the guilty feeling because your projects move "too slowly", but for spare time projects there really is no such thing, and you should definitely not worry about it.

keep up the great work! packages like these are the reason i switched from vim to emacs. thanks again.
