### ISSUE TITLE
Generated function names are non-deterministic

### ISSUE THREAD

**Issue by PythonNut** [PythonNut/evil-easymotion#36]
Currently, function names are produced using the following scheme:

``` emacs
(eval-and-compile
  (defun evilem--unquote (exp)
    "Return EXP unquoted."
    (while (member (car-safe exp) '(quote function))
      (setq exp (cadr exp)))
    exp)

  (defun evilem--make-name (func)
    (format "evilem--motion-%s-%s"
            (if (functionp func)
                (symbol-name (evilem--unquote func))
              (mapconcat (lambda (f)
                           (symbol-name (evilem--unquote f)))
                         func
                         "-"))
            (symbol-name (cl-gensym)))))
```

This is bad because function names are not portable (not even on the same machine, but different times). This should be fixed somehow.

**Comment by PythonNut** [comment]
Does anything bad actually happen if we just omit the `(symbol-name (cl-gensym))` part?

**Comment by noctuid** [comment]
As far as I can tell, the only time there could be a collision is if the user used `evilem-create` with the same motion(s) multiple times with different settings. I think it would probably be best to get rid of the gensym and make the user responsible for dealing with name clashes by providing an optional argument to override the default for the resulting function name.

**Comment by PythonNut** [comment]
@noctuid at least for now, the canonical way to specify the name for a motion is to use `evilem-make-motion`/`evilem-make-motion-plain`, and pass a name.

**Comment by wkf** [comment]
Hey there, I believe this change introduced #39. The default bindings for t/T and f/F seem to call `evilem-define` (and `evilem-create`) with the same name, so the bindings for t and f are getting overwritten.

**Comment by PythonNut** [comment]
@wkf Ahh... I remember now why I did the whole garbage thing to begin with.

**Comment by noctuid** [comment]
I think the best approach is just to make the user specify different names in `evilem-define` too when necessary.
