### ISSUE TITLE
Support avy-resume

### ISSUE THREAD

**Issue by noctuid** [PythonNut/evil-easymotion#37]
As mentioned in abo-abo/avy#165, this just requires using `avy-with`. 

Using `avy-with` would have other potential upsides. It would allow the user to change the keys for specific commands by altering `avy-keys-alist` (or the style by altering `avy-styles-alist`). These both could be done with `:bind` though.

**Comment by PythonNut** [comment]
I just really hope I didn't break anything.

**Comment by JacksonGariety** [comment]
When I start evil-easymode and hit "SPC j" it says:

    Symbol's value as a variable is void: avy-keys-alist
