### ISSUE TITLE
canceling an easymotion

### ISSUE THREAD

**Issue by braham-snyder** [PythonNut/evil-easymotion#38]
Currently, doing, e.g., `d SPC j <escape>` deletes one line for me--is this expected behavior? Would it be difficult to instead do nothing?

**Comment by PythonNut** [comment]
No idea, but I agree that doing nothing would be preferred.

**Comment by PythonNut** [comment]
Okay, so to be clear this is only an issue when the motion is composed with an operator. I'm not really sure what happens after a `keyboard-quit` during this phase, so I can't guess at why it's deleting anyway.

**Comment by PythonNut** [comment]
Actually, I thought about this for a bit more, and I guess when the easymotion is cancelled the point is not moved, so only the current line is deleted. Something similar happens if you go `d#G` where `#` is the current line number.

I doubt there's much I can do about this.
