### ISSUE TITLE
SPC * doesn't work (or gets stuck on first symbol searched for)

### ISSUE THREAD

**Issue by bpstahlman** [PythonNut/evil-easymotion#40]
When I first open emacs, I can generally do one successful `SPC *` search. Subsequently, hitting `SPC *` on another symbol shows matches for the original target, not the one point is currently on. At some point (usually after switching to another buffer/file), the command seems to stop working altogether. After that, hitting `SPC *` on any symbol simply displays `zero candidates` in the status area.

Hmm... Just noticed that I can get `SPC *` to work again temporarily (for one search only) by running `evil-search-word-forward` while positioned on the desired symbol. Note that after that, `SPC *` will once again display targets, but only for the symbol most recently searched with `evil-search-word-forward`, not for whatever symbol point happens to be on.

Am I completely misunderstanding how `SPC *` is supposed to work? Is it perhaps meant to be used in conjunction with other commands? Is there documentation on any of this? I didn't see much on the various search types in the README...

**Comment by PythonNut** [comment]
@bpstahlman Yes, the word search motions have always been a bit weird, and I've had trouble reproducing the problem in the past. Hence https://github.com/PythonNut/evil-easymotion/issues/30.

I'll take another look at it.

**Comment by bpstahlman** [comment]
Sounds good. Thanks!

On Jan 24, 2017 6:16 PM, "Jonathan Hayase" <notifications@github.com> wrote:

@bpstahlman <https://github.com/bpstahlman> Yes, the word search motions
have always been a bit weird, and I've had trouble reproducing the problem
in the past. Hence #30
<https://github.com/PythonNut/evil-easymotion/issues/30>.

I'll take another look at it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/PythonNut/evil-easymotion/issues/40#issuecomment-274981639>,
or mute the thread

**Comment by PythonNut** [comment]
As far as I can tell, this works now. Let me know if this is still an issue.
