### ISSUE TITLE
Installation fails with 'avy' not provided error

### ISSUE THREAD

**Issue by RafalLukawiecki** [PythonNut/evil-easymotion#41]
Apologies if this is a mistake of my own making, but I cannot seem to install evil-easymotion. Despite avy being pre-installed, install-package for evil-easymotion returns:
```
Compiling file /Users/rafal/.emacs.d/elpa/evil-easymotion-20170110.2004/evil-easymotion.el at Wed Apr 12 23:16:40 2017
Entering directory ‘/Users/rafal/.emacs.d/elpa/evil-easymotion-20170110.2004/’
evil-easymotion.el:63:13:Error: Required feature ‘avy’ was not provided
```
However, I can see avy is present in my ```~/.emacs.d/elpa/avy-20170208.148```

Deleting both packages and reinstalling did not help. Many thanks for any tips.

**Comment by PythonNut** [comment]
`avy` needs to be available at compile time.

You can test if it is by trying to `(require 'avy)` just before you attempt to install `evil-easymotion`. If this works, but the installation still fails, I'll have to look into it.

**Comment by RafalLukawiecki** [comment]
Thank you for your reply. Indeed, avy was downloaded but it was not loading with require. For some reason, an older version was installing itself (Jan 2017). I had to delete all the downloaded packages and I let them all reinstall. This solved the problem for me. Thanks again.
