### ISSUE TITLE
search all words with a command

### ISSUE THREAD

**Issue by fourcolors** [PythonNut/evil-easymotion#42]
Hey, 

So I use easy motion in VIM by pushing `s` and it searches all words on the page. I can then push the one or two characters required to get to that point from there. 

I like this because I only have to press at max, 3 characters to get to any part of the page. 

Is this set-up possible for with evil-easymotion?

**Comment by PythonNut** [comment]
Isn't that `evil-avy-goto-word-0`?

**Comment by fourcolors** [comment]
@PythonNut I'm a little new to all this, I'll check.

**Comment by fourcolors** [comment]
Yeah, that commands works, I wonder, would it be possible to have it include spaces?

**Comment by fourcolors** [comment]
What's the point of easymotion if avy is doing this? I'm confused.

**Comment by thriveth** [comment]
IN Vim Easymotion, leader-W will show all words forward in the visible window, with one selection character for the closest ones, two for the following ones, then three etc. 

Avy does it wrong by always having at least two characters to type in, or sometimes 3. Evil-em does it right but for some reason only lets you chose words in the same line. 

Wouldn't it be possible to emulate Vim-EasyMotion's behavior completely?

**Comment by PythonNut** [comment]
@thriveth I don't think that would be very easy to implement, since `avy` doesn't support things like that.

**Comment by 9527KGG** [comment]
+1

**Comment by PythonNut** [comment]
As far as I can tell, there are no remaining actionable items here, so I am closing this.
