### ISSUE TITLE
unable to get this to work

### ISSUE THREAD

**Issue by fourcolors** [PythonNut/evil-easymotion#44]
I'm unable to get this to work at all. 

I'm using spacemacs and configured it with something like 

```
   dotspacemacs-additional-packages '(
                                      all-the-icons
                                      fish-mode
                                      evil-easymotion
                                      )
```

Maybe I don't understand the docs well enough but I'm not able to see any of the eaysmotion commands?

**Comment by fourcolors** [comment]
Can you update your docs to reflect how to get the example you show in the video working? I'm really confused on how I can get that behavior.

**Comment by PythonNut** [comment]
@fourcolors, basic usage is covered in the README, I don't use spacemacs, so I can't comment on things specific to that configuration, unfortunately. :(

**Comment by wbolster** [comment]
@fourcolors you should bind the commands somehow, and `SPC` might not be the best option since i thinks it's already used by spacemacs. see the readme for details on how to bind to a (different) prefix.

**Comment by PythonNut** [comment]
If you have further questions, feel free to continue here, but I'm closing since this seems like a non-issue as far as the code is concerned.
