### ISSUE TITLE
Package isn't being found in spacemacs

### ISSUE THREAD

**Issue by fourcolors** [PythonNut/evil-easymotion#45]
Hey, I think I know whats happening, I can't find `evil-easymotion` when doing a `package-install` in spacemacs. Any idea how to find and install the package?

**Comment by PythonNut** [comment]
@fourcolors `evil-easymotion` is on MELPA, I can't comment on spacemacs since I don't use it, but do you have MELPA in your `package-archives`?

**Comment by ShirajG** [comment]
Same issue here. If I manually add evil-easymotion to my additonal packages, I get the following error: evil-easymotion.el:311:1:Error: Symbol’s function definition is void: evilem--compute-inclusivity

Spacemacs does come with melpa enabled as a package source.

**Comment by PythonNut** [comment]
As far as I know, the package compiles fine when installed from MELPA. (This may be due to some changes I made.) So I can closing this for now.
