### ISSUE TITLE
motion only on visible characters

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [PythonNut/evil-easymotion#46]
I made a function `void-WORD-beg` which collects candidates on the the entire window. I a large org file, when I folded all the headings I noticed that the the function took a long time. I think this is because it was traversing the lines that were the folded, not just the visible lines. 

how I can make a motion traverse only visible text?

`  (evilem-make-motion void-WORD-beg #'evil-forward-WORD-begin :scope 'page
:push-jump t
:initial-point (lambda () (move-to-window-line 0)))
`

**Comment by Luis-Henriquez-Perez** [comment]
I figured out how to do this. It involves skipping over overlays.
I used wrapped this macro around the functions I used to make a motion 
(ie. `(+with-ignore-invisible-overlays (evil-forward-word-begin))`)

    (defmacro +with-ignore-invisible-overlays (&rest form)
      "Form should be a callable that returns a point based on the current point."
      (let ((search-fun (car form))
            (args (rest form))
            (overlay nil)
            (point nil))
        `(progn
           (setq point ,@form)
           (setq overlay (ov-at (point))) 
           (while (and overlay (member 'invisible (ov-prop overlay)))
             (goto-char (ov-end overlay))
             (setq point ,@form)
             (setq overlay (ov-at (point))))
           point)))

I write about it more in depth in [this question](https://emacs.stackexchange.com/questions/39300/re-search-forward-through-visible-text-only/39324#39324) on the emacs stackexchange. 

I propose adding something like this to easymotion because it doesn't ever make sense to search for candidates that are hidden.

**Comment by PythonNut** [comment]
You'd like this behavior to be the default for all motions?

**Comment by Luis-Henriquez-Perez** [comment]
I think this may have been fixed in `avy`. I just refactored my code and this wasn't an issue anymore. I'm currently just using `avy` and not `easymotion`. Just to be safe I'll install `easymotion` and test it on my (very large) init.org file. I'll get back to you.

**Comment by PythonNut** [comment]
I thought about your implementation, and I decided that it makes sense to have it on by default. Sorry for taking so long. The behavior is controlled by the `:include-invisible` argument, which is `nil` by default.
