### ISSUE TITLE
Word motion only working within a line

### ISSUE THREAD

**Issue by calmofthestorm** [PythonNut/evil-easymotion#50]
Has anyone else encountered motions only working within a line? I set (evilem-default-keybindings "SPC"), and then SPC-w works as expected, but only on the current line -- I can jump forward or backward to any word on the current line, but it does not show jump points on other lines. SPC-j/k work as expected.

I'm encountering this with only evil and easymotion enabled, on emacs 25.2.2 on Debian.

**Comment by PythonNut** [comment]
This is by design. See the example definition:
```elisp
(evilem-make-motion
 evilem-motion-forward-word-begin #'evil-forward-word-begin
:scope 'line)
```
If you want to remove this restriction, remove the `:scope 'line`.

**Comment by calmofthestorm** [comment]
Thanks!

**Comment by ghosty141** [comment]
Sorry for digging this up but how are you supposed to remove the scope 'line? Edit the source? It would be nice if you could set the scope via the config.

**Comment by PythonNut** [comment]
You can always just re-define the motions yourself by putting this in your config:

```emacs
(with-eval-after-load 'evil-easymotion
  (eval-when-compile (require 'evil-easymotion))
  (evilem-make-motion evilem-motion-forward-word-begin #'evil-forward-word-begin)
  (evilem-make-motion evilem-motion-forward-WORD-begin #'evil-forward-WORD-begin)
  (evilem-make-motion evilem-motion-forward-word-end #'evil-forward-word-end)
  (evilem-make-motion evilem-motion-forward-WORD-end #'evil-forward-WORD-end)
  (evilem-make-motion evilem-motion-backward-word-begin #'evil-backward-word-begin)
  (evilem-make-motion evilem-motion-backward-WORD-begin #'evil-backward-WORD-begin)
  (evilem-make-motion evilem-motion-backward-word-end #'evil-backward-word-end)
  (evilem-make-motion evilem-motion-backward-WORD-end #'evil-backward-WORD-end))
```

**Comment by ghosty141** [comment]
Thanks for the answer :) Is there a reason why it is intended to only run on one line? (just curious)
