### ISSUE TITLE
Add bidirectional find

### ISSUE THREAD

**Issue by rsheasby** [PythonNut/evil-easymotion#54]
Hi.

I know this issue was discussed in #10 and it seems like you were keen to add it but it never happened despite you saying it wouldn't be much work. Your previous rationale seemed to be that it's not much mental energy to decide on a direction but it is another keystroke to hold down shift while pressing the find key. Additionally, many people are migrating from vim which does have the bidirectional find so having it missing is more mental effort for those who are used to it.

**Comment by PythonNut** [comment]
I'm pretty sure it is supported, you would just need to define the motion yourself. For example:
```emacs
(evilem-make-motion
   evilem-motion-line (list #'next-line #'previous-line)
   :pre-hook (setq evil-this-type 'line)
   :bind ((temporary-goal-column (current-column))
          (line-move-visual nil)))
```
You can combine an arbitrary set of motions this way.
