### ISSUE TITLE
How to correctly load evil-easymotion from melpa?

### ISSUE THREAD

**Issue by 9527KGG** [PythonNut/evil-easymotion#57]
Hello, I am new to emacs (from vim). Here is my .emacs

(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

;; bootstrap use-package
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)

(use-package evil
  :ensure t ;; install the evil package if not installed
  :init ;; tweak evil's configuration before loading it
  (setq evil-search-module 'evil-search)
  (setq evil-ex-complete-emacs-commands nil)
  (setq evil-vsplit-window-right t)
  (setq evil-split-window-below t)
  (setq evil-shift-round nil)
  (setq evil-want-C-u-scroll t)
  :config ;; tweak evil after loading it
  (evil-mode))

(use-package evil-easymotion
  :config
  (evilem-default-keybindings "SPC"))

Emacs always prompts "
Error (use-package): Cannot load evil-easymotion.
"

May you please give me some suggestion?

**Comment by 9527KGG** [comment]
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

;; bootstrap use-package
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)

(use-package evil
  :ensure t ;; install the evil package if not installed
  :init ;; tweak evil's configuration before loading it
  (setq evil-search-module 'evil-search)
  (setq evil-ex-complete-emacs-commands nil)
  (setq evil-vsplit-window-right t)
  (setq evil-split-window-below t)
  (setq evil-shift-round nil)
  (setq evil-want-C-u-scroll t)
  :config ;; tweak evil after loading it
  (evil-mode)

  (use-package evil-easymotion
    :config
    (evilem-default-keybindings "SPC")))
    
does not work either.

Thanks.

**Comment by 9527KGG** [comment]
For now, I just need evil and evil-easymotion. thanks.

**Comment by PythonNut** [comment]
Perhaps try
```elisp
(use-package evil-easymotion
  :ensure t
  :config
  (evilem-default-keybindings "SPC")))
```
Note the added `:ensure t`. I can't promise this'll work, since I haven't tested it, though.

**Comment by 9527KGG** [comment]
Thanks, it works! May I ask one more Q:

By default, SPC w only searchs the word in current line. However change it to whole file?

I notice 

_:scope object

An object to limit the scope of an easymotion. object may be any thing understood by thing-at-point. In practice, object will often be 'line._

I want to change the scope from line to whole file. But I don't know how add the setting to .emacs. 

Thanks.
