### ISSUE TITLE
Integration with evil-snipe

### ISSUE THREAD

**Issue by NightMachinary** [PythonNut/evil-easymotion#58]
How can I use this with https://github.com/hlissner/evil-snipe? I like to be able to type the first two letters of any word I want to jump onto, and then select among the candidates ala easymotion.

**Comment by PythonNut** [comment]
There's a couple snippets already in [the wiki](https://github.com/PythonNut/evil-easymotion/wiki/Integrating-with-evil-snipe) that I believe should already do this.

**Comment by NightMachinary** [comment]
I saw sth to the effect that the wiki was outdated in the issues, so I
didn’t check it out. Sorry and thanks!

**Comment by PythonNut** [comment]
As far as I know, the wiki examples for `evil-snipe` do work, so I am closing this.
