### ISSUE TITLE
Bug report: remove extra jump point on parenthesis/bracket/square

### ISSUE THREAD

**Issue by 9527KGG** [PythonNut/evil-easymotion#59]
Repro: 

My .emacs has
(evilem-make-motion
 evilem-motion-forward-word-begin #'evil-forward-word-begin
:scope )

(evilem-make-motion
 evilem-motion-forward-word-end #'evil-forward-word-end
:scope )

(evilem-make-motion
 evilem-motion-backward-word-begin #'evil-backward-word-begin
:scope )

(evilem-make-motion
 evilem-motion-backward-word-end #'evil-backward-word-end
:scope )

I have this example file:

(abc)
[abc]
{abc}

press \<leader\>w

Observed:
![image](https://user-images.githubusercontent.com/12282281/63640840-0aad5a00-c65a-11e9-80f0-4bf2f9a6ca0c.png)
each line has 3 jump point.

Expected:
Same as Vim easy motion. Each line has only 1 jump point.
![image](https://user-images.githubusercontent.com/12282281/63640853-32042700-c65a-11e9-98a7-e3b360cca635.png)

Comments:
These extra jump points are very bad when writing source code. There are ton of  parenthesis/bracket/square in the source, making people hard to use. People has type much more in evil easymotion than vim easy motion.

Thanks.

**Comment by PythonNut** [comment]
This merely reflects the points that the evil word motions would take you to, which are based on the Emacs version of a "word" which is more fine than the corresponding notion in Vim. To fix this, you would have to define new word motions which match the vim motions.

**Comment by kgfly** [comment]
Closed.

(After many tries, finally to give up Emacs and stick to neovim ^_^  )
