### ISSUE TITLE
[Request] Implement evilem-motion-search-region-(backward/forward)

### ISSUE THREAD

**Issue by WhatDothLife** [PythonNut/evil-easymotion#60]
Since there are commands like `evilem-motion-search-word-backward` and  `evilem-motion-search-word-forward`, there should also exist commands that search for occurrences of the currently marked region instead of the word at point. 

Is it possible that this will be implemented soon?

**Comment by PythonNut** [comment]
I believe this can already be implemented. In particular, you can use `:bind` to store the contents of the region in a variable and then make a motion that reads that variable and searches for it. You may need to use a `:pre-hook` to deactivate the region first.
