### ISSUE TITLE
easymotion doesn't work in Info-mode

### ISSUE THREAD

**Issue by WhatDothLife** [PythonNut/evil-easymotion#64]
When calling M-x `+evil/easymotion` in Info-mode I receive the following error:
> evil-define-key*: Key sequence SPC : starts with non-prefix key SPC

Interestingly, calling the function with it's associated binding(I bound it to `gs`) results in Emacs hanging itself.
I'm not the only one experiencing this kind of issue, see [here](https://github.com/hlissner/doom-emacs/issues/2653#event-3126543437). So far Info-mode has been the only mode where this behavior occured.

**Comment by PythonNut** [comment]
Wait is this issue for `evil-avy-goto-char-2`? Either way it's pretty bizarre.

**Comment by WhatDothLife** [comment]
This has been solved in the meantime. Wasn't an issue of easymotion, sorry for reporting it here.
