### ISSUE TITLE
How to change prefix from `gs` to `SPC SPC`

### ISSUE THREAD

**Issue by tusqasi** [PythonNut/evil-easymotion#69]
I want to use evilem like the vim-em. So, I want to change the default of `gs` to `SPC SPC`.

How can one do this?

I am a complete noob with. emacs.

I am using doom BTW.

**Comment by PythonNut** [comment]
Is `evil-easymotion` included in `doom` by default?

**Comment by PythonNut** [comment]
Wow, it appears that it is. [Here](https://github.com/hlissner/doom-emacs/blob/473417a8907559f0a60952ddcae8db861445a533/modules/editor/evil/config.el#L571-L578) is the code that binds the prefix to <kbd>g</kbd><kbd>s</kbd>. Does that help you?

**Comment by tusqasi** [comment]
Sorry forgot about this issue I raised.
I got an answer from the doom discord which works for me.

` (map! :leader "SPC" (cmd! (set-transient-map evilem-map)))`

**Comment by tusqasi** [comment]
I am yet to learn about lisp, that block you shared is pretty much over my head for now.

I will sure look into your solution also.

**Comment by tusqasi** [comment]
And would, adding this to the FAQ section, be a good idea?

I think many people might want to change the keymap. (I can be wrong here, and also I don't yet know how emacs people solve problems)

**Comment by tusqasi** [comment]
> Is `evil-easymotion` included in `doom` by default?

No don't think so.
I had to add a few lines to `package.el` and had to run `package-install` command in the `M-x` menu and then I could use evil-em.

```lisp
(package! evil-easymotion
 :recipe (:host github :repo "PythonNut/evil-easymotion"
          :files ("evil-easymotion.el")))
(package! el-patch
 :recipe (:host github :repo "raxod502/el-patch"
          :files ("el-patch.el")))
```

**Comment by PythonNut** [comment]
> I am yet to learn about lisp, that block you shared is pretty much over my head for now.

Ah yes sorry about that. 

> And would, adding this to the FAQ section, be a good idea?

I think the issue is that your problem is specific to `doom`. Different configurations have different conventions for setting key mappings, so I don't think it really makes sense to try to cover all of them here.

**Comment by tusqasi** [comment]
> I think the issue is that your problem is specific to doom. Different configurations have different conventions for setting key mappings, so I don't think it really makes sense to try to cover all of them here.

Right, I got it now.

Thanks.
