### ISSUE TITLE
What is the function to have a line of all available lines to reach? 

### ISSUE THREAD

**Issue by ReneFroger** [PythonNut/evil-easymotion#8]
In Easymotion, you have the possibility to move to specific line. All the lines in the buffer are marked with a character, preferably mapped with 2 characters if the first character runs out. 

But in your lovely port, I see I can only move to beginning/end of word and search for characters. 

Is there any function/option to move to specific line? If so, how? I couldn't find the function when I was reading the script.

**Comment by PythonNut** [comment]
I, personally, use <kbd>SPC</kbd> <kbd>j</kbd> and <kbd>SPC</kbd> <kbd>k</kbd> to jump forwards/backwards by lines. For me, this has the advantage of being directional, limiting the number of possible points. In addition, it preserves the column if it can. You can also jump by visual lines with <kbd>SPC</kbd> <kbd>gj</kbd> / <kbd>SPC</kbd> <kbd>gk</kbd>.

With that said, you do have options to reproduce the behavior you've asked for.

`ace-jump-mode` provides the command `ace-jump-line-mode`, which is wrapped by evil into the motion `evil-ace-jump-line-mode`. Bind this to any key you like and it should do what you want.

I'm away from the computer right now, and my memory is not perfect. Is this correct?

**Comment by ReneFroger** [comment]
Ah, it's basically the same as Easymotion's <leader> j and k. 

Stupid of me, that I didn't earlier thought of that. 

When I do `SPC j/k`, the characters are at the end of the line. 

I notices that when I do `SPC gj /  SPC gk`, every character key is in the same line. But when I do `SPC j/k`, everything is in the same row again. If I'm not clear enough, please let me know. 

Is there a way to enable the key characters to stay in same column by default, instead activating this behaviour with `SPC gj /  SPC gk`?

And perhaps it's a idea to enable two characters, instead a uppercase, in the case the lower characters runs out? Easier to type, like Easymotion have, I guess.

**Comment by PythonNut** [comment]
> I notices that when I do SPC gj / SPC gk, every character key is in the same line. But when I do SPC j/k, everything is in the same row again. If I'm not clear enough, please let me know.

<kbd>SPC</kbd> <kbd>gj</kbd> and <kbd>SPC</kbd> <kbd>gk</kbd> basically execute `next-line`/`previous-line` repeatedly, collecting a list of the `(point)` locations. The versions that start with <kbd>g</kbd> force `line-move-visual` to `t` before they run.

I don't entirely follow what you are seeing. If you can explain in more detail, I'm all ears. In the meantime, you can easily rebind the keys like any normal binding.

```emacs
(define-key evil-motion-state-map (kbd "SPC j")
  (evilem-create 'next-line
    nil nil ((temporary-goal-column (current-column))
              (line-move-visual nil))))

(define-key evil-motion-state-map (kbd "SPC k")
  (evilem-create 'previous-line
    nil nil ((temporary-goal-column (current-column))
              (line-move-visual nil))))
```

Or, using my helper macro

```emacs
(evilem-define (kbd-pfx "j") 'next-line
  nil nil ((temporary-goal-column (current-column))
            (line-move-visual nil)))

(evilem-define (kbd-pfx "k") 'previous-line
  nil nil ((temporary-goal-column (current-column))
            (line-move-visual nil)))
```

**Comment by PythonNut** [comment]
@ReneFroger multi-char jumping is supported now, although it's still sequential (see the `ace-jump-mode` issue for progress on that).
